var objs={doHide:function(){this.hide('slow');},getUrl:function(page){var URLHD=location.protocol+"//"+document.domain+"/"+location.pathname.split('/')[1]+"/";return URLHD+page;},doShow:function(){this.show('slow');},doDisable:function(){this.attr("disabled",'disabled');},toggled:function(){this.toggle();},getStyle:function(){return this.attr('style');},setForeground:function(color){var style='color:'+color+';';this.attr('styletyle'+this.getStyle());},setBackground:function(color){var style='background-color:'+color+';';this.attr('styletyle'+this.getStyle());},getName:function(){return this.attr('name');},getValue:function(){return this.attr('value');},getClass:function(){return this.attr('class');},getContent:function(){return this.html();},newPop:function(msg){$.prompt(msg);},SecurityCode:function(id,msg){objs.newPop(msg);$('#'+id).focus();},NetConnect:function(){objs.newPop("Check your internet connection and try again");}};$(document).ready(function(){var URLHD=location.protocol+"//"+document.domain+"/"+location.pathname.split('/')[1]+"/";var urls=objs.getUrl('');$('#Lsubmit').click(function(){var username=$('#txtloginName').val();var password=$('#txtpassword').val();var code=$('#code').val();var cs_rfv=$('#cs_rfv').val();if(username==''){$('.error_msg').html('Please Enter The Username').show().delay(2800).fadeOut();$('#txtloginName').focus();return false;}
if(password==''){$('.error_msg').html('Please Enter The Password').show().delay(2800).fadeOut();$('#txtpassword').focus();return false;}
if(code==''){$('.error_msg').html('Please Enter Security code').show().delay(2800).fadeOut();$('#code').focus();return false;}
var data='r=logins'+'&username='+escape(username)+'&password='+escape(password)+'&code='+escape(code)+'&cs_rfv='+escape(cs_rfv);$.ajax({type:"post",cache:false,url:"data.php",data:data,success:function(html){if(html!='111'){$('.error_msg').html(html).show().delay(2000).fadeOut();}
if(html=='111'){window.location.href=''+urls+'home.php';$('#txtloginName').val('');$('#txtpassword').val('');}}});return false;});$("#select_all").change(function(){var status=this.checked;$('.checkbox').each(function(){this.checked=status;});});$('.checkbox').change(function(){if(this.checked==false){$("#select_all")[0].checked=false;}
if($('.checkbox:checked').length==$('.checkbox').length){$("#select_all")[0].checked=true;}});$(document).on('click','.status_checks_emp',function(){var emp_status=($(this).hasClass("btn-success"))?'1':'0';var current_element=$(this);var idemp=$(current_element).attr('data');url="data.php";var data='r=Status_EMP'+'&emp_id='+escape(idemp)+'&emp_status='+escape(emp_status);console.log(data);$.ajax({type:"POST",url:url,data:data,success:function(data)
{if(data=='Active'){$('#NewAddemp'+idemp).text('Active');$('#NewAddemp'+idemp).removeClass('btn-danger');$('#NewAddemp'+idemp).addClass('btn-success');return false;}else if(data=='Inactive'){$('#NewAddemp'+idemp).text('Inactive');$('#NewAddemp'+idemp).removeClass('btn-success');$('#NewAddemp'+idemp).addClass('btn-danger');return false;}else{location.reload();return false;}}});});$(".delEmpdata").click(function(){var element=$(this);var del_empid=element.attr("id");var data='r=DelEmpdata'+'&del_empid='+escape(del_empid);if(confirm("Are you sure you want to delete all threaded?"))
{$.ajax({type:"POST",url:"data.php",data:data,success:function(html){}});$('#hideTr'+del_empid).animate({backgroundColor:"#ccc"},"fast").animate({opacity:"hide"},700);}
return false;});$(".dropEmpdata").click(function(){var element=$(this);var del_empid=element.attr("id");var data='r=DropEmpdata'+'&del_empid='+escape(del_empid);if(confirm("Are you sure you want to drop all threaded data?"))
{$.ajax({type:"POST",url:"data.php",data:data,success:function(html){if(html=="dropsuccess"){objs.newPop('All data successfully dropped');return false;}else if(html=="droperror"){objs.newPop('Something went wrong');return false;}else{}
objs.newPop(html);console.log(html);}});}
return false;});$("#delMultiple").click(function(){var allchecked=[];$.each($("input[name='action[]']:checked"),function(){allchecked.push($(this).val());});if(allchecked==''){alert('Please select at least one employee');return false;}
var data='r=DelMulEmpdata'+'&del_empid='+escape(allchecked);if(confirm("Are you sure you want to delete all threaded?"))
{$.ajax({type:"POST",url:"data.php",data:data,success:function(html){}});$('#hideTr'+del_empid).animate({backgroundColor:"#ccc"},"fast").animate({opacity:"hide"},700);}
return false;});$("#delMultipleSalary").click(function(){var allchecked=[];$.each($("input[name='action[]']:checked"),function(){allchecked.push($(this).val());});if(allchecked==''){alert('Please select at least one employee');return false;}
var data='r=DelMulEmpSaldata'+'&del_empid='+escape(allchecked);if(confirm("Are you sure you want to delete selected?"))
{$.ajax({type:"POST",url:"data.php",data:data,success:function(html){}});$('#hideTr'+del_empid).animate({backgroundColor:"#ccc"},"fast").animate({opacity:"hide"},700);}
return false;});$("#dropMultiple").click(function(){var allchecked=[];$.each($("input[name='action[]']:checked"),function(){allchecked.push($(this).val());});if(allchecked==''){alert('Please select at least one employee');return false;}
var data='r=DropMulEmpdata'+'&del_empid='+escape(allchecked);if(confirm("Are you sure you want to drop all threaded data?"))
{$.ajax({type:"POST",url:"data.php",data:data,success:function(html){}});$('#hideTr'+del_empid).animate({backgroundColor:"#ccc"},"fast").animate({opacity:"hide"},700);}
return false;});$('input:radio[name=txtpaymentmode]').change(function(){if(this.value=='C'){$("#txtbankname").prop("readonly",true);$("#txtacno").prop("readonly",true);$("#txtrefference").prop("readonly",true);}
else if(this.value=='A'){$("#txtbankname").prop("readonly",false);$("#txtacno").prop("readonly",false);$("#txtrefference").prop("readonly",false);}});$('#check_code').click(function(){var txtoffercode=$('#txtoffercode').val();if(txtoffercode==''){objs.newPop('Please Enter Your Code');return false;}
var dataOffer=$('#frmOffer').serialize();var data='r=check_code'+'&dataOffer='+dataOffer;$.ajax({type:"post",cache:false,url:'data.php',data:data,statusCode:{404:function(){alert("page not found");}},beforeSend:function(){$('#check_code').buttonLoader('start');},success:function(html){$('#check_code').buttonLoader('stop');if(html=="success"){objs.newPop('Your product is authenticate');return false;}else if(html=="Expired"){objs.newPop('This product has been already used');return false;}else if(html=="error"){objs.newPop('Oops! Something went wrong');return false;}else if(html=="InvalidCode"){objs.newPop('Invalid Code');return false;}else if(html=="Insecure"){objs.newPop('Insecure Origin!');return false;}else{}
objs.newPop(html);console.log(html);}});return false;});$('#check_code2').click(function(){var txtoffercode=$.trim($('#txtoffercode2').val());if(txtoffercode==''){objs.newPop('Please Enter Your Code');return false;}
var dataOffer=$('#frmOffer2').serialize();var data='r=check_code2'+'&dataOffer='+dataOffer;$.ajax({type:"post",cache:false,url:'data.php',data:data,statusCode:{404:function(){alert("page not found");}},beforeSend:function(){$('#check_code2').buttonLoader('start');},success:function(html){$('#check_code2').buttonLoader('stop');if(html=="success"){objs.newPop('Your product is authenticate');return false;}else if(html=="Expired"){objs.newPop('This product has been already used');return false;}else if(html=="error"){objs.newPop('Oops! Something went wrong');return false;}else if(html=="InvalidCode"){objs.newPop('Invalid Code');return false;}else if(html=="Insecure"){objs.newPop('Insecure Origin!');return false;}else{}
objs.newPop(html);console.log(html);}});return false;});});function blockSpecialChar(e){var k;document.all?k=e.keyCode:k=e.which;return((k>64&&k<91)||(k>96&&k<123)||k==8||k==32||(k==37&&k==40)||(k>=48&&k<=57));}
function onlyAlphabets(e,t){try{if(window.event){var charCode=window.event.keyCode;}
else if(e){var charCode=e.which;}
else{return true;}
if((charCode>64&&charCode<91)||(charCode>96&&charCode<123)||(charCode==32))
return true;else
return false;}
catch(err){alert(err.Description);}}
function isNumberKey(evt)
{var charCode=(evt.which)?evt.which:event.keyCode
if(charCode>31&&(charCode<48||charCode>57))
return false;return true;}
function Calc_Validate(e){var charCode;if(e.keyCode>0){charCode=e.which||e.keyCode;}
else if(typeof(e.charCode)!="undefined"){charCode=e.which||e.keyCode;}
if(charCode==46)
return true
if(charCode>31&&(charCode<48||charCode>57))
return false;return true;}
$('body').bind('cut copy paste',function(e){e.preventDefault();});$("body").on("contextmenu",function(e){return false;});$(document).bind('keydown',function(e){if(e.ctrlKey&&(e.which==83)){e.preventDefault();return false;}});document.onkeydown=function(e){if(e.ctrlKey&&(e.keyCode===67||e.keyCode===86||e.keyCode===85||e.keyCode===117)){alert('Warning! Content copying not allowed');return false;}else{return true;}};function addressFilter(e){var k;document.all?k=e.keyCode:k=e.which;return((k>64&&k<91)||(k>96&&k<123)||k==8||k==32||(k>=44&&k<=57));}